"""Generate examples/furniture/.gitlab-ci.yml.

Single source of truth: edit FURNITURE here, re-run, commit the YAML.

Pipeline shape:
    lint                  (1 job)
      ↓
    build_<item>          (50 jobs, one per furniture item)
      ↓
    test_<item>           (20 jobs, only for the first 20 items)
      ↓
    deploy_<item>         (50 jobs, when: manual)
"""
from __future__ import annotations

from pathlib import Path

FURNITURE: list[str] = [
    # First 20 — these have a paired test_<item>.
    "chair", "sofa", "fridge", "table", "desk",
    "bed", "bookshelf", "cabinet", "wardrobe", "dresser",
    "nightstand", "ottoman", "bench", "stool", "recliner",
    "loveseat", "sectional", "coffee_table", "end_table", "dining_table",
    # Next 30 — build + deploy only, no test.
    "console_table", "vanity", "hutch", "sideboard", "buffet",
    "china_cabinet", "armoire", "chest", "footstool", "bar_stool",
    "rocking_chair", "lounge_chair", "accent_chair", "swivel_chair", "lamp",
    "mirror", "rug", "curtain", "shelf", "drawer",
    "mattress", "pillow", "blanket", "headboard", "footboard",
    "bunk_bed", "daybed", "futon", "hammock", "crib",
]
TESTED_COUNT = 20
TESTED: list[str] = FURNITURE[:TESTED_COUNT]


def render() -> str:
    out: list[str] = [
        "# Generated by examples/furniture/generate.py — do not edit by hand.",
        "stages:",
        "  - lint",
        "  - build",
        "  - test",
        "  - deploy",
        "",
        "lint:",
        "  stage: lint",
        "  script:",
        "    - flake8 .",
        "",
    ]

    for item in FURNITURE:
        out += [
            f"build_{item}:",
            "  stage: build",
            "  needs: [lint]",
            "  script:",
            f"    - make build_{item}",
            "",
        ]

    for item in TESTED:
        out += [
            f"test_{item}:",
            "  stage: test",
            f"  needs: [build_{item}]",
            "  script:",
            f"    - make test_{item}",
            "",
        ]

    for item in FURNITURE:
        out += [
            f"deploy_{item}:",
            "  stage: deploy",
            f"  needs: [build_{item}]",
            "  when: manual",
            "  script:",
            f"    - make deploy_{item}",
            "",
        ]

    return "\n".join(out)


def main() -> None:
    target = Path(__file__).parent / ".gitlab-ci.yml"
    target.write_text(render())
    print(f"wrote {target} ({len(FURNITURE)} build/deploy jobs, {len(TESTED)} test jobs)")


if __name__ == "__main__":
    main()
